Table: MyNumbers

+-------------+------+
| Column Name | Type |
+-------------+------+
| num         | int  |
+-------------+------+
This table may contain duplicates (In other words, there is no primary key for this table in SQL).
Each row of this table contains an integer.


A single number is a number that appeared only once in the MyNumbers table.

Find the largest single number. If there is no single number, report null.

The result format is in the following example.



Example 1:

Input:
MyNumbers table:
+-----+
| num |
+-----+
| 8   |
| 8   |
| 3   |
| 3   |
| 1   |
| 4   |
| 5   |
| 6   |
+-----+
Output:
+-----+
| num |
+-----+
| 6   |
+-----+
Explanation: The single numbers are 1, 4, 5, and 6.
Since 6 is the largest single number, we return it.
Example 2:

Input:
MyNumbers table:
+-----+
| num |
+-----+
| 8   |
| 8   |
| 7   |
| 7   |
| 3   |
| 3   |
| 3   |
+-----+
Output:
+------+
| num  |
+------+
| null |
+------+
Explanation: There are no single numbers in the input table so we return null.

In [1]:
import pandas as pd

def biggest_single_number(my_numbers: pd.DataFrame) -> pd.DataFrame:
    # Считаем количество вхождений каждого числа в столбце 'num'
    counts = my_numbers['num'].value_counts()

    # Оставляем только те числа, которые встречаются ровно один раз
    single_numbers = counts[counts == 1].index

    # Если такие числа есть, находим максимальное
    if not single_numbers.empty:
        result = pd.DataFrame({'num': [max(single_numbers)]})
    else:
        # Если нет чисел, которые встречаются ровно один раз, возвращаем DataFrame с значением None
        result = pd.DataFrame({'num': [None]})

    return result

In [2]:
# Пример данных
data = {'num': [8, 8, 3, 3, 1, 4]}
my_numbers = pd.DataFrame(data)

# Применяем функцию
result = biggest_single_number(my_numbers)
print(result)

   num
0    4